#Ce fichier permet la création et le lancement des différents conteneurs docker utiles pour le projet
#Ici , nous souhaitons lancer 3 conteneurs , un pour mySQL (language de base de données), un pour phpMyAdmin
#(permettant la visualisation globale de la BDD) ainsi que notre application flask .

version: '3'
networks:
  lan_network:
    driver: bridge
services:
  pfrapplication:
      restart: always
      hostname: back
      build: .
      ports:
        - 5000:5000
      links:
        - dbm:mysql
      depends_on:
        - dbm
      networks:
        -  lan_network

  phpmyadmin:
    restart: always
    hostname: phpmyadmin
    image: nazarpc/phpmyadmin
    links:
      - dbm:mysql
    depends_on:
      - dbm
    ports:
      - 8181:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: password
    networks:
      - lan_network

  dbm:
    restart: always
    hostname: mysql
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - /var/log/mysql-db:/var/log/mysql
      - /var/lib/mysql:/var/lib/mysql
      - ./sql/:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      -  lan_network
